version: '3.9'

services:
  db:
    container_name: eto_baza
    image: postgres
    networks:
      - back
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  telegram-bot-api:
    image: python
    expose:
      - 8080
    container_name: telezka
    build:
      context: ${SERVICE_1_SRC_DIR}
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
    networks:
      - back
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/cert/
    depends_on:
      - telegram-bot-api
    ports:
      - 80:80
      - 443:443

networks:
  back:
    driver: bridge

volumes:
  postgres:
